[package]
name = "csa"
version = "0.1.0"
authors = ["Tristram Gr√§bener <tristramg@gmail.com>"]

[dependencies]
csv = "1.0.0-beta.5"
serde = "1.0.15"
serde_derive = "1.0.15"
chrono = "0.4"
regex = "0.2"
lazy_static = "0.2"
itertools = "0.7.2"
failure = "0.1.1"
cpuprofiler = "0.0.3"
structopt = "0.1.0"
structopt-derive = "0.1.0"
